// import "./modules/keyboard";
import "./modules/baseConfig";
import "./modules/ipcPenetrate";
import "./modules/ipcFile";
import "./modules/ipcWin";
import "./modules/ipcScreen";
import "./modules/MenuManger";
import "./modules/store";
import "./modules/ffmpeg";
import "./modules/tts";
